import { useState } from "react";
import { AlertTriangle, Bot, CheckCircle2, GitCompareArrows, KeyRound, Network, Save, ShieldCheck } from "lucide-react";
import { finalizeSchema, updateEntity, updateRelationship, validateSchema } from "../../../api/graphAnalyzer";
import type { GraphEntity, GraphRelationship, GraphSchema } from "../../../contracts/graphAnalyzer";
import { AnalyzerLayout } from "../components/AnalyzerLayout";
import { SchemaCanvas } from "../components/SchemaCanvas";
import { schemaChanges } from "../schemaChanges";
import { useGraphAnalyzer } from "../GraphAnalyzerContext";
import { useAnalyzerBootstrap, useAnalyzerMutation, useSchemas } from "../analyzerQueries";

type Mode = "PROPOSED" | "EXISTING" | "CHANGES" | "SIDE_BY_SIDE";

export function SchemaWorkspacePage() {
  const schemas = useSchemas();
  const ui = useGraphAnalyzer();
  const [mode, setMode] = useState<Mode>("PROPOSED");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const validation = useAnalyzerMutation(validateSchema);
  const finalize = useAnalyzerMutation(finalizeSchema);
  const saveEntity = useAnalyzerMutation(updateEntity);
  const saveRelationship = useAnalyzerMutation(updateRelationship);
  const existing = schemas.data?.existing ?? null;
  const proposed = schemas.data?.proposed ?? null;
  const displaySchema = mode === "EXISTING" ? existing : proposed;
  const changes = proposed === null ? [] : schemaChanges(existing, proposed);
  const selectedEntity = proposed?.entities.find((entity) => entity.id === selectedId) ?? null;
  const selectedRelationship = proposed?.relationships.find((relationship) => relationship.id === selectedId) ?? null;
  // The last validation the *server* recorded, with this session's fresh result
  // preferred when there is one. Reading only `validation.data` meant the panel
  // went blank on navigation and the Finalize button re-locked itself, because
  // mutation state does not survive a remount -- so a proposal validated a
  // moment earlier looked unvalidated.
  const bootstrap = useAnalyzerBootstrap();
  const currentValidation = validation.data ?? bootstrap.data?.validation ?? undefined;

  return <AnalyzerLayout><div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-500">System graph workspace</p><h2 className="mt-1 text-2xl font-semibold text-white">Review and refine the graph model</h2><p className="mt-1 text-sm text-slate-400">Source mappings are references only. Every edit below changes the system graph proposal—never a source system.</p></div><div className="flex gap-2"><button type="button" disabled={validation.isPending || proposed === null} onClick={() => { validation.mutate(undefined); }} className="inline-flex items-center gap-2 rounded-lg border border-emerald-700 px-3 py-2 text-sm text-emerald-200 disabled:opacity-40"><ShieldCheck size={15} />{validation.isPending ? "Validating…" : "Validate proposal"}</button><button type="button" disabled={finalize.isPending || proposed === null || (currentValidation?.status ?? "BLOCKING") === "BLOCKING"} onClick={() => { finalize.mutate(undefined); }} className="rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-emerald-950 disabled:opacity-40">{finalize.isPending ? "Finalizing…" : "Finalize schema"}</button></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-emerald-950 bg-[#0a1714] p-2"><div className="flex gap-1">{(["PROPOSED", "EXISTING", "CHANGES", "SIDE_BY_SIDE"] as const).map((item) => <button type="button" key={item} onClick={() => { setMode(item); }} className={`rounded-lg px-3 py-2 text-xs font-medium ${mode === item ? "bg-emerald-950 text-emerald-200" : "text-slate-500 hover:text-white"}`}>{item.replaceAll("_", " ")}</button>)}</div><div className="flex items-center gap-3 px-2 text-xs"><Legend color="bg-emerald-400" label="Added" /><Legend color="bg-amber-400" label="Changed" /><Legend color="bg-red-400" label="Removed" /></div></div>
    {schemas.isLoading ? <div className="h-[560px] animate-pulse rounded-xl bg-white/[.035]" /> : proposed === null ? <div className="grid min-h-96 place-items-center rounded-xl border border-dashed border-emerald-900 bg-[#0a1714] text-center"><div><Network className="mx-auto text-slate-700" size={34} /><h3 className="mt-3 font-medium text-slate-300">No proposed schema</h3><p className="mt-1 text-sm text-slate-500">Select source objects in Graph Analyzer and complete analysis first.</p></div></div> : mode === "CHANGES" ? <ChangesList changes={changes} onSelect={setSelectedId} /> : mode === "SIDE_BY_SIDE" ? <div className="grid gap-4 xl:grid-cols-2"><SchemaPane label="Existing system graph" schema={existing} selectedId={selectedId} onSelect={setSelectedId} /><SchemaPane label="Proposed system graph · editable" schema={proposed} selectedId={selectedId} onSelect={setSelectedId} /></div> : displaySchema === null ? <div className="rounded-xl border border-dashed border-emerald-900 p-10 text-center text-slate-500">No existing system graph. This is a valid first-time setup.</div> : <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]"><SchemaCanvas schema={displaySchema} selectedId={selectedId} onSelect={setSelectedId} />{mode === "PROPOSED" ? <SchemaInspector entity={selectedEntity} relationship={selectedRelationship} entities={proposed.entities} saving={saveEntity.isPending || saveRelationship.isPending} error={saveEntity.error?.message ?? saveRelationship.error?.message ?? null} onSaveEntity={(entity) => { saveEntity.mutate(entity); }} onSaveRelationship={(relationship) => { saveRelationship.mutate(relationship); }} onChat={(graphObjectId) => { ui.openChat({ workspace: "SCHEMA", selectedGraphObjectId: graphObjectId }); }} /> : <ReadOnlyInspector entity={displaySchema.entities.find((entity) => entity.id === selectedId) ?? null} relationship={displaySchema.relationships.find((relationship) => relationship.id === selectedId) ?? null} />}</div>}
    {(currentValidation !== undefined || validation.isError || finalize.isError) ? <section className="rounded-xl border border-emerald-950 bg-[#0a1714] p-4"><h3 className="font-semibold text-white">Validation</h3>{validation.isError || finalize.isError ? <p role="alert" className="mt-2 text-sm text-red-300">{validation.error?.message ?? finalize.error?.message}</p> : null}{currentValidation !== undefined ? <div className="mt-3 space-y-2"><p className={`text-sm ${currentValidation.status === "BLOCKING" ? "text-red-300" : "text-emerald-300"}`}>{currentValidation.status === "VALID" ? "Proposal is valid and ready to finalize." : `${String(currentValidation.issues.length)} issue(s) require review.`}</p>{currentValidation.issues.map((issue) => <button type="button" key={issue.id} onClick={() => { setSelectedId(issue.objectId); }} className="flex w-full items-start gap-2 rounded-lg border border-emerald-950 p-3 text-left text-sm"><AlertTriangle size={15} className={issue.severity === "BLOCKING" ? "text-red-400" : "text-amber-400"} /><span><span className="block text-slate-300">{issue.message}</span><span className="text-xs text-slate-600">{issue.code}</span></span></button>)}</div> : null}</section> : null}
  </div></AnalyzerLayout>;
}

function SchemaPane({ label, schema, selectedId, onSelect }: { readonly label: string; readonly schema: GraphSchema | null; readonly selectedId: string | null; readonly onSelect: (id: string) => void }) { return <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</h3>{schema === null ? <div className="grid h-[560px] place-items-center rounded-xl border border-dashed border-emerald-900 text-sm text-slate-500">No existing graph</div> : <SchemaCanvas schema={schema} selectedId={selectedId} onSelect={onSelect} />}</section>; }
function Legend({ color, label }: { readonly color: string; readonly label: string }) { return <span className="flex items-center gap-1.5 text-slate-500"><span className={`size-2 rounded-full ${color}`} />{label}</span>; }
function ChangesList({ changes, onSelect }: { readonly changes: ReturnType<typeof schemaChanges>; readonly onSelect: (id: string) => void }) { return <div className="rounded-xl border border-emerald-950 bg-[#0a1714] p-4"><div className="mb-3 flex items-center gap-2"><GitCompareArrows size={16} className="text-emerald-400" /><h3 className="font-semibold text-white">Existing → proposed</h3><span className="text-xs text-slate-600">{String(changes.length)} changes</span></div><div className="space-y-2">{changes.map((change) => <button type="button" key={`${change.type}:${change.id}`} onClick={() => { onSelect(change.id); }} className="flex w-full items-center justify-between rounded-lg border border-emerald-950 px-4 py-3 text-left hover:bg-white/[.025]"><span className="text-sm text-slate-300">{change.label}</span><span className="rounded bg-emerald-950 px-2 py-1 text-[10px] text-emerald-300">{change.type}</span></button>)}{changes.length === 0 ? <p className="p-6 text-center text-sm text-slate-500">No differences between the schemas.</p> : null}</div></div>; }

function SchemaInspector({ entity, relationship, entities, saving, error, onSaveEntity, onSaveRelationship, onChat }: { readonly entity: GraphEntity | null; readonly relationship: GraphRelationship | null; readonly entities: readonly GraphEntity[]; readonly saving: boolean; readonly error: string | null; readonly onSaveEntity: (entity: GraphEntity) => void; readonly onSaveRelationship: (relationship: GraphRelationship) => void; readonly onChat: (id: string) => void }) {
  if (entity === null && relationship === null) return <aside className="rounded-xl border border-emerald-950 bg-[#0a1714] p-5"><Network className="text-slate-700" /><p className="mt-3 text-sm text-slate-500">Select an entity or relationship to inspect and edit the proposal.</p></aside>;
  return <aside className="rounded-xl border border-emerald-950 bg-[#0a1714] p-5">{entity !== null ? <EntityEditor key={entity.id} entity={entity} saving={saving} onSave={onSaveEntity} onChat={onChat} /> : relationship !== null ? <RelationshipEditor key={relationship.id} relationship={relationship} entities={entities} saving={saving} onSave={onSaveRelationship} onChat={onChat} /> : null}{error !== null ? <p role="alert" className="mt-3 text-xs text-red-300">Save failed: {error}</p> : null}<p className="mt-4 border-t border-emerald-950 pt-3 text-[11px] leading-5 text-emerald-300"><ShieldCheck className="mr-1 inline" size={13} />Edits update only the proposed system graph configuration.</p></aside>;
}

function EntityEditor({ entity, saving, onSave, onChat }: { readonly entity: GraphEntity; readonly saving: boolean; readonly onSave: (entity: GraphEntity) => void; readonly onChat: (id: string) => void }) { const [draft, setDraft] = useState(entity); return <div><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wider text-emerald-500">Entity</span><button type="button" onClick={() => { onChat(entity.id); }} className="text-emerald-300" aria-label="Discuss entity"><Bot size={16} /></button></div><label className="mt-3 block text-xs text-slate-500">Name<input value={draft.name} onChange={(event) => { setDraft({ ...draft, name: event.target.value }); }} className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2 text-sm text-white" /></label><label className="mt-3 block text-xs text-slate-500">Description<textarea value={draft.description} onChange={(event) => { setDraft({ ...draft, description: event.target.value }); }} rows={3} className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2 text-sm text-white" /></label><h4 className="mt-4 text-xs font-semibold uppercase tracking-wider text-slate-500">Properties</h4><div className="mt-2 max-h-64 space-y-2 overflow-y-auto">{draft.properties.map((property) => <div key={property.id} className="rounded-lg border border-emerald-950 p-3"><div className="flex items-center justify-between"><span className="font-mono text-xs text-emerald-200">{property.name}</span><span className="text-[10px] text-slate-600">{property.dataType}</span></div><div className="mt-2 flex gap-3 text-[10px]"><label className="flex items-center gap-1 text-violet-300"><input type="checkbox" checked={property.identifier} onChange={(event) => { setDraft({ ...draft, properties: draft.properties.map((item) => item.id === property.id ? { ...item, identifier: event.target.checked } : item) }); }} /><KeyRound size={11} />Identifier</label><label className="flex items-center gap-1 text-sky-300"><input type="checkbox" checked={property.indexed} onChange={(event) => { setDraft({ ...draft, properties: draft.properties.map((item) => item.id === property.id ? { ...item, indexed: event.target.checked } : item) }); }} />System graph index</label></div><p className="mt-2 truncate text-[10px] text-slate-600">Mapping: {property.sourceObjectId ?? "unmapped"} {property.sourceField ?? ""}</p></div>)}</div><button type="button" disabled={saving || draft.name.trim().length === 0} onClick={() => { onSave(draft); }} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-400 px-3 py-2 text-sm font-semibold text-emerald-950 disabled:opacity-40"><Save size={14} />{saving ? "Saving…" : "Save entity"}</button></div>; }

function RelationshipEditor({ relationship, entities, saving, onSave, onChat }: { readonly relationship: GraphRelationship; readonly entities: readonly GraphEntity[]; readonly saving: boolean; readonly onSave: (relationship: GraphRelationship) => void; readonly onChat: (id: string) => void }) { const [draft, setDraft] = useState(relationship); return <div><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wider text-emerald-500">Relationship</span><button type="button" onClick={() => { onChat(relationship.id); }} className="text-emerald-300" aria-label="Discuss relationship"><Bot size={16} /></button></div><label className="mt-3 block text-xs text-slate-500">Type<input value={draft.name} onChange={(event) => { setDraft({ ...draft, name: event.target.value.toUpperCase().replaceAll(" ", "_") }); }} className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2 text-sm text-white" /></label><label className="mt-3 block text-xs text-slate-500">Start entity<select value={draft.fromEntityId} onChange={(event) => { setDraft({ ...draft, fromEntityId: event.target.value }); }} className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2 text-sm text-white">{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label className="mt-3 block text-xs text-slate-500">End entity<select value={draft.toEntityId} onChange={(event) => { setDraft({ ...draft, toEntityId: event.target.value }); }} className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2 text-sm text-white">{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label className="mt-3 block text-xs text-slate-500">Direction<select value={draft.direction} onChange={(event) => { setDraft({ ...draft, direction: event.target.value as GraphRelationship["direction"] }); }} className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2 text-sm text-white"><option value="OUTBOUND">Outbound</option><option value="INBOUND">Inbound</option></select></label><p className="mt-3 text-[10px] text-slate-600">Source mapping: {draft.sourceObjectId ?? "unmapped"}</p><button type="button" disabled={saving || draft.name.length === 0 || draft.fromEntityId === draft.toEntityId} onClick={() => { onSave(draft); }} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-400 px-3 py-2 text-sm font-semibold text-emerald-950 disabled:opacity-40"><Save size={14} />{saving ? "Saving…" : "Save relationship"}</button></div>; }

function ReadOnlyInspector({ entity, relationship }: { readonly entity: GraphEntity | null; readonly relationship: GraphRelationship | null }) { return <aside className="rounded-xl border border-emerald-950 bg-[#0a1714] p-5">{entity !== null ? <><p className="text-xs uppercase tracking-wider text-slate-500">Existing entity</p><h3 className="mt-2 font-semibold text-white">{entity.name}</h3><p className="mt-2 text-sm text-slate-500">{entity.properties.length} properties · {entity.constraints.length} constraints</p></> : relationship !== null ? <><p className="text-xs uppercase tracking-wider text-slate-500">Existing relationship</p><h3 className="mt-2 font-semibold text-white">{relationship.name}</h3></> : <p className="text-sm text-slate-500">Select a graph object.</p>}<p className="mt-4 text-xs text-emerald-400"><CheckCircle2 className="mr-1 inline" size={13} />Read-only existing system graph</p></aside>; }
