import { useEffect, useState } from "react";
import { AlertTriangle, Bot, CheckCircle2, Clock3, History, Play, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import { startSync } from "../../../api/graphAnalyzer";
import type { SyncMode, SyncRun } from "../../../contracts/graphAnalyzer";
import { AnalyzerLayout } from "../components/AnalyzerLayout";
import { SourceTree } from "../components/SourceTree";
import { useGraphAnalyzer } from "../GraphAnalyzerContext";
import { useAnalyzerBootstrap, useAnalyzerMutation, useSyncRun } from "../analyzerQueries";
import { formatTimestamp } from "../../../format/datetime";

export function SyncWorkspacePage() {
  const bootstrap = useAnalyzerBootstrap();
  const ui = useGraphAnalyzer();
  const [mode, setMode] = useState<SyncMode>("PARTIAL");
  const [scope, setScope] = useState<ReadonlySet<string>>(() => new Set());
  const [activeId, setActiveId] = useState<string | null>(bootstrap.data?.activeSync?.id ?? null);
  const start = useAnalyzerMutation(({ syncMode, selected }: { readonly syncMode: SyncMode; readonly selected: readonly string[] }) => startSync(syncMode, selected));
  const active = useSyncRun(activeId);
  const finalized = bootstrap.data?.proposedSchema?.status === "FINALIZED";
  const run = active.data ?? bootstrap.data?.activeSync ?? null;
  // Refresh the workspace header once a run reaches a terminal state.
  //
  // Depends on the *status string*, not on `active.data` and `bootstrap`:
  // react-query hands back a new object identity on every render, so the
  // previous dependency list re-ran this effect continuously and refetched the
  // bootstrap query in a loop for as long as the page was open.
  const runStatus = active.data?.status ?? null;
  const refetchBootstrap = bootstrap.refetch;
  useEffect(() => {
    if (runStatus !== null && !["PREPARING", "RUNNING"].includes(runStatus)) void refetchBootstrap();
  }, [runStatus, refetchBootstrap]);

  const begin = () => { start.mutate({ syncMode: mode, selected: mode === "FULL" ? [] : [...scope] }, { onSuccess: (next) => { setActiveId(next.id); } }); };
  return <AnalyzerLayout><div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-500">System graph synchronization</p><h2 className="mt-1 text-2xl font-semibold text-white">Read sources. Write the system graph.</h2><p className="mt-1 text-sm text-slate-400">Synchronization is one-way. Configured sources are never modified or used as rollback targets.</p></div>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_350px]"><section className="rounded-xl border border-emerald-950 bg-[#0a1714] p-5"><div className="flex gap-2">{(["PARTIAL", "FULL"] as const).map((item) => <button key={item} type="button" onClick={() => { setMode(item); }} className={`rounded-lg px-4 py-2 text-sm font-medium ${mode === item ? "bg-emerald-400 text-emerald-950" : "border border-emerald-950 text-slate-400"}`}>{item === "PARTIAL" ? "Partial sync" : "Full sync"}</button>)}</div>
      {mode === "PARTIAL" ? <div className="mt-5"><div className="mb-4"><h3 className="font-semibold text-white">Select source scope</h3><p className="mt-1 text-sm text-slate-400">Only selected objects are read; graph writes follow the finalized mappings.</p></div><SourceTree sources={bootstrap.data?.sources ?? []} selectedIds={scope} activeId={null} onSelectionChange={setScope} onActivate={() => undefined} /></div> : <div className="mt-5 rounded-xl border border-emerald-950 bg-[#07120f] p-5"><h3 className="font-semibold text-white">Finalized graph scope</h3><p className="mt-2 text-sm leading-6 text-slate-400">Reads every source object referenced by finalized mappings and upserts the resulting nodes and relationships into the designated system graph.</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Included sources" value={String(bootstrap.data?.sources.filter((source) => source.status === "CONNECTED").length ?? 0)} /><Metric label="Schema version" value={String(bootstrap.data?.proposedSchema?.version ?? "—")} /></div></div>}
      <div className="mt-5 rounded-lg border border-emerald-900/70 bg-emerald-950/25 p-3 text-xs leading-5 text-emerald-200"><ShieldCheck className="mr-2 inline" size={15} />Target: System Graph. Sources are queried through bounded read-only connector methods; no source write, schema change, or rollback mutation is permitted.</div>
      {!finalized ? <div role="alert" className="mt-4 flex gap-2 rounded-lg border border-amber-800 bg-amber-950/30 p-3 text-sm text-amber-200"><AlertTriangle size={16} className="mt-0.5 shrink-0" />Finalize a valid proposed schema before synchronization.</div> : null}{start.isError ? <p role="alert" className="mt-3 text-sm text-red-300">Sync could not start: {start.error.message}</p> : null}
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={() => { ui.openChat({ workspace: "SYNC", selectedScope: [...scope], syncRunId: run?.id }); }} className="inline-flex items-center gap-2 text-sm text-emerald-300"><Bot size={15} />Review synchronization impact</button><button type="button" disabled={!finalized || start.isPending || ["PREPARING", "RUNNING"].includes(run?.status ?? "") || (mode === "PARTIAL" && scope.size === 0)} onClick={begin} className="inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-950 disabled:cursor-not-allowed disabled:opacity-40"><Play size={15} />{start.isPending ? "Starting…" : mode === "FULL" ? "Start full sync" : `Start partial sync (${String(scope.size)})`}</button></div>
    </section><SyncProgress run={run} loading={active.isLoading && run === null} /></div>
    <SyncHistory runs={bootstrap.data?.syncHistory ?? []} onInspect={setActiveId} />
  </div></AnalyzerLayout>;
}

function SyncProgress({ run, loading }: { readonly run: SyncRun | null; readonly loading: boolean }) { if (loading) return <aside className="h-80 animate-pulse rounded-xl bg-white/[.035]" />; if (run === null) return <aside className="grid min-h-80 place-items-center rounded-xl border border-dashed border-emerald-900 bg-[#0a1714] p-6 text-center"><div><RefreshCw className="mx-auto text-slate-500" size={28} /><h3 className="mt-3 font-medium text-slate-300">No synchronization active</h3><p className="mt-1 text-sm text-slate-400">Configure a scope to see real progress and results.</p></div></aside>; const active = ["PREPARING", "RUNNING"].includes(run.status); return <aside className="rounded-xl border border-emerald-950 bg-[#0a1714] p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-slate-400">Current run</p><h3 className="mt-1 font-semibold text-white">{run.mode.toLowerCase()} synchronization</h3></div>{active ? <Clock3 className="animate-pulse text-emerald-400" /> : run.status === "COMPLETED" ? <CheckCircle2 className="text-emerald-400" /> : <XCircle className="text-red-400" />}</div><div className="mt-5 space-y-3"><ProgressRow label="State" value={run.status.replaceAll("_", " ")} /><ProgressRow label="Activity" value={run.currentActivity} /><ProgressRow label="Current source" value={run.currentSource ?? "—"} /><ProgressRow label="Current object" value={run.currentObject ?? "—"} /></div><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Items read" value={String(run.itemsRead)} /><Metric label="Processed" value={String(run.itemsProcessed)} /><Metric label="Nodes written" value={String(run.nodesWritten)} /><Metric label="Relationships" value={String(run.relationshipsWritten)} /></div>{run.failedItems > 0 || run.error !== null ? <div className="mt-4 rounded-lg border border-red-900 bg-red-950/30 p-3 text-sm text-red-200">{run.failedItems} failed items. {run.error}</div> : null}<p className="mt-4 text-[10px] text-slate-400">Started {formatTimestamp(run.startedAt)} · Run {run.id}</p></aside>; }
function ProgressRow({ label, value }: { readonly label: string; readonly value: string }) { return <div className="flex items-start justify-between gap-3 border-b border-emerald-950 pb-2 text-xs"><span className="text-slate-400">{label}</span><span className="text-right capitalize text-slate-300">{value}</span></div>; }
function Metric({ label, value }: { readonly label: string; readonly value: string }) { return <div className="rounded-lg border border-emerald-950 bg-[#07120f] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold text-slate-200">{value}</p></div>; }
function SyncHistory({ runs, onInspect }: { readonly runs: readonly SyncRun[]; readonly onInspect: (id: string) => void }) { return <section className="rounded-xl border border-emerald-950 bg-[#0a1714] p-5"><div className="mb-4 flex items-center gap-2"><History size={16} className="text-emerald-400" /><h3 className="font-semibold text-white">Synchronization history</h3></div>{runs.length === 0 ? <div className="rounded-lg border border-dashed border-emerald-950 p-6 text-center text-sm text-slate-400">No synchronization history yet.</div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Started</th><th className="pb-3">Mode</th><th className="pb-3">Status</th><th className="pb-3">Processed</th><th className="pb-3">Graph writes</th><th /></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-t border-emerald-950"><td className="py-3 text-slate-400">{formatTimestamp(run.startedAt)}</td><td className="py-3 text-slate-300">{run.mode}</td><td className="py-3"><span className={`rounded px-2 py-1 text-xs ${run.status === "COMPLETED" ? "bg-emerald-950 text-emerald-300" : run.status === "FAILED" ? "bg-red-950 text-red-300" : "bg-amber-950 text-amber-300"}`}>{run.status.replaceAll("_", " ")}</span></td><td className="py-3 text-slate-400">{run.itemsProcessed}</td><td className="py-3 text-slate-400">{run.nodesWritten + run.relationshipsWritten}</td><td className="py-3 text-right"><button type="button" onClick={() => { onInspect(run.id); }} className="text-xs text-emerald-300">Inspect</button></td></tr>)}</tbody></table></div>}</section>; }
