export type DependencyStatus =
  | "HEALTHY"
  | "DEGRADED"
  | "UNAVAILABLE"
  | "STARTING"
  | "UNKNOWN";


export type DependencyErrorCode =
  | "TIMEOUT"
  | "CONNECTION_REFUSED"
  | "AUTH_FAILED"
  | "HEALTH_CHECK_FAILED"
  | "QUERY_FAILED"
  | "UNINITIALIZED"
  | "QUEUE_SATURATED"
  | "UNKNOWN_ERROR";


export type FreshnessStatus =
  | "LIVE"
  | "CACHED"
  | "STALE";


export type DependencyProbeResult = {
  readonly status: DependencyStatus;
  readonly latency_ms: number | null;

  /**
   * UTC ISO 8601 timestamp generated by the backend.
   */
  readonly checked_at: string;

  readonly error_code: DependencyErrorCode | null;
  readonly safe_message: string | null;
};


export type WarningMeta = {
  readonly source: string;
  readonly code: string;
  readonly message: string;
};


export type PageMeta = {
  readonly next_cursor: string | null;
  readonly has_more: boolean;
  readonly page_size: number;
};


export type ResponseMeta = {
  readonly schema_version: string;
  readonly request_id: string;

  /**
   * UTC ISO 8601 timestamp indicating when the response was generated.
   */
  readonly generated_at: string;

  readonly freshness: FreshnessStatus;
  readonly partial: boolean;
  readonly warnings: readonly WarningMeta[];
};


export type APIResponse<T> = {
  readonly data: T | null;
  readonly page: PageMeta | null;
  readonly meta: ResponseMeta;
};


export type InfrastructureOverview =
  Readonly<Record<string, DependencyProbeResult>>;