from typing import Protocol, Any, Optional

class ConfigurationView(Protocol):
    def section(self, name: str) -> Any: ...
    @property
    def release_id(self) -> str: ...

class ConfigurationHandle(Protocol):
    def current(self) -> ConfigurationView: ...
    def pinned(self, release_id: str) -> ConfigurationView: ...
