from typing import Any, Protocol

from return_platform.platform.contracts.epoch import RuntimeEpoch


class ConfigurationView(Protocol):
    def section(self, name: str) -> Any: ...
    @property
    def release_id(self) -> str: ...
    @property
    def checksum(self) -> str: ...


class ConfigurationHandle(Protocol):
    def current(self, epoch: RuntimeEpoch) -> ConfigurationView: ...
    async def pinned(self, release_id: str) -> ConfigurationView: ...
