import { lazy } from "react";
import { LayoutDashboard, Database, FileCheck2, HardDrive, Search, Network, Import, Download, Activity, Briefcase, Zap, Shield, Settings, CheckSquare, RotateCcw, Headphones, Bot, TestTube2, ShieldAlert, ServerCog, DatabaseZap } from "lucide-react";

export type RouteCapability =
  | "LIVE"
  | "FIXTURE"
  | "BLOCKED";

export type RouteDefinition = {
  path: string;
  name: string;
  icon?: React.ComponentType<{ size?: number; className?: string }>;
  capability: RouteCapability;
  component: React.LazyExoticComponent<React.ComponentType<unknown>>;
  navigable: boolean;
  group?: "Associate" | "Customer" | "Support" | "Operations" | "Logistics" | "Warehouse" | "Tracking" | "AI Gateway" | "Explore" | "Data Operations" | "Sandbox & AI" | "Governance" | "System";
};

export const routes: RouteDefinition[] = [
  {
    path: "/associate/returns",
    name: "Returns Assistant",
    icon: Bot,
    capability: "LIVE",
    navigable: true,
    group: "Associate",
    component: lazy(() => import("./features/operations/AssociateReturnsPage").then(m => ({ default: m.AssociateReturnsPage }))),
  },
  {
    path: "/operations/returns/:sessionId",
    name: "Operations Return Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.OperationsReturnDetailPage }))),
  },
  {
    path: "/operations/return-agents",
    name: "Return Agents",
    icon: Bot,
    capability: "LIVE",
    navigable: true,
    group: "Operations",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.ReturnAgentsPage }))),
  },
  {
    path: "/logistics/returns",
    name: "Logistics Returns",
    icon: RotateCcw,
    capability: "LIVE",
    navigable: true,
    group: "Logistics",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.LogisticsReturnsPage }))),
  },
  {
    path: "/warehouse/returns",
    name: "Warehouse Returns",
    icon: HardDrive,
    capability: "LIVE",
    navigable: true,
    group: "Warehouse",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.WarehouseReturnsPage }))),
  },
  {
    path: "/tracking/returns",
    name: "Return Tracking",
    icon: Activity,
    capability: "LIVE",
    navigable: true,
    group: "Tracking",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.TrackingReturnsPage }))),
  },
  {
    path: "/customer/returns",
    name: "My Returns",
    icon: RotateCcw,
    capability: "LIVE",
    navigable: true,
    group: "Customer",
    component: lazy(() => import("./features/operations/CustomerReturnsPages").then(m => ({ default: m.CustomerReturnsPage }))),
  },
  {
    path: "/customer/returns/new",
    name: "Create Return",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/operations/AssociateReturnsPage").then(m => ({ default: m.AssociateReturnsPage }))),
  },
  {
    path: "/customer/returns/:sessionId",
    name: "Return Timeline",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/operations/CustomerReturnsPages").then(m => ({ default: m.CustomerReturnDetailPage }))),
  },
  {
    path: "/support/returns",
    name: "Support Returns",
    icon: Headphones,
    capability: "LIVE",
    navigable: true,
    group: "Support",
    component: lazy(() => import("./features/operations/SupportPages").then(m => ({ default: m.SupportReturnsPage }))),
  },
  {
    path: "/return-support/workbench",
    name: "Returns Support Workbench",
    icon: Headphones,
    capability: "LIVE",
    navigable: true,
    group: "Support",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.ReturnSupportWorkbenchPage }))),
  },
  {
    path: "/support/returns/:sessionId",
    name: "Support Return Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/operations/SupportPages").then(m => ({ default: m.SupportReturnDetailPage }))),
  },
  {
    path: "/support/review-queue",
    name: "Review Queue",
    icon: ShieldAlert,
    capability: "LIVE",
    navigable: true,
    group: "Support",
    component: lazy(() => import("./features/operations/SupportPages").then(m => ({ default: m.SupportReviewQueuePage }))),
  },
  {
    path: "/support/operations",
    name: "Operations",
    icon: ServerCog,
    capability: "LIVE",
    navigable: true,
    group: "Support",
    component: lazy(() => import("./features/operations/SupportPages").then(m => ({ default: m.SupportOperationsPage }))),
  },
  {
    path: "/ai-gateway/requests",
    name: "AI Requests",
    icon: Bot,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/AIGatewayPages").then(m => ({ default: m.AIRequestsPage }))),
  },
  {
    path: "/ai-gateway/routes",
    name: "AI Routes",
    icon: Network,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.AIRoutesPage }))),
  },
  {
    path: "/ai-gateway/tasks",
    name: "AI Tasks",
    icon: CheckSquare,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.AITasksPage }))),
  },
  {
    path: "/ai-gateway/metrics",
    name: "AI Metrics",
    icon: Activity,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.AIMetricsPage }))),
  },
  {
    path: "/ai-gateway/safety",
    name: "AI Safety",
    icon: ShieldAlert,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.AISafetyPage }))),
  },
  {
    path: "/ai-gateway/requests/:requestId",
    name: "AI Request Inspector",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/operations/AIGatewayPages").then(m => ({ default: m.AIRequestDetailPage }))),
  },
  {
    path: "/ai-gateway/simulator",
    name: "AI Simulator",
    icon: TestTube2,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/AIGatewayPages").then(m => ({ default: m.AISimulatorPage }))),
  },
  {
    path: "/ai-gateway/interceptions",
    name: "Interceptions",
    icon: ShieldAlert,
    capability: "LIVE",
    navigable: true,
    group: "AI Gateway",
    component: lazy(() => import("./features/operations/AIGatewayPages").then(m => ({ default: m.AIInterceptionsPage }))),
  },
  {
    path: "/system/dependencies",
    name: "Dependencies",
    icon: ServerCog,
    capability: "LIVE",
    navigable: true,
    group: "System",
    component: lazy(() => import("./features/operations/SystemPages").then(m => ({ default: m.DependenciesPage }))),
  },
  {
    path: "/system/integration-outbox",
    name: "Integration Outbox",
    icon: ServerCog,
    capability: "LIVE",
    navigable: true,
    group: "System",
    component: lazy(() => import("./features/operations/OperationalWorkspacePages").then(m => ({ default: m.IntegrationOutboxPage }))),
  },
  {
    path: "/system/dependencies/:dependencyId",
    name: "Dependency Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/operations/SystemPages").then(m => ({ default: m.DependencyDetailPage }))),
  },
  {
    path: "/seed-data",
    name: "Seed Data",
    icon: DatabaseZap,
    capability: "LIVE",
    navigable: true,
    group: "System",
    component: lazy(() => import("./features/operations/SystemPages").then(m => ({ default: m.SeedDataPage }))),
  },
  {
    path: "/system/dependency-simulator",
    name: "Dependency Simulator",
    icon: TestTube2,
    capability: "LIVE",
    navigable: true,
    group: "System",
    component: lazy(() => import("./features/dependency-simulator/OverviewPage").then(m => ({ default: m.OverviewPage }))),
  },
  {
    path: "/system/dependency-simulator/omc",
    name: "OMC Simulator",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/dependency-simulator/OmcPage").then(m => ({ default: m.OmcPage }))),
  },
  {
    path: "/system/dependency-simulator/parcel",
    name: "Parcel Simulator",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/dependency-simulator/ParcelPage").then(m => ({ default: m.ParcelPage }))),
  },
  {
    path: "/system/dependency-simulator/freight",
    name: "Freight Simulator",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/dependency-simulator/FreightPage").then(m => ({ default: m.FreightPage }))),
  },
  {
    path: "/system/dependency-simulator/lsi",
    name: "LSI Simulator",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/dependency-simulator/LsiPage").then(m => ({ default: m.LsiPage }))),
  },
  {
    path: "/system/dependency-simulator/ai-metrics",
    name: "Simulator AI Metrics",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/dependency-simulator/AiMetricsPage").then(m => ({ default: m.AiMetricsPage }))),
  },
  {
    path: "/system/dependency-simulator/operations/:operationId",
    name: "Simulation Operation",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/dependency-simulator/OperationDetailPage").then(m => ({ default: m.OperationDetailPage }))),
  },
  {
    path: "/overview",
    name: "Overview",
    icon: LayoutDashboard,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/OverviewPage").then(m => ({ default: m.OverviewPage }))),
  },
  {
    path: "/data-console/schema",
    name: "Model & Schema",
    icon: Database,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/DataStudioPages").then(m => ({ default: m.SchemaCatalogPage }))),
  },
  {
    path: "/data-console/ai-studio",
    name: "AI Studio",
    icon: Bot,
    capability: "LIVE",
    navigable: true,
    group: "Sandbox & AI",
    component: lazy(() => import("./features/data-console/pages/DataStudioPages").then(m => ({ default: m.AIStudioPage }))),
  },
  {
    path: "/data-console/graph-sync",
    name: "Graph Sync",
    icon: Network,
    capability: "LIVE",
    navigable: true,
    group: "Data Operations",
    component: lazy(() => import("./features/data-console/pages/DataStudioPages").then(m => ({ default: m.GraphSyncPage }))),
  },
  {
    path: "/data-console/feedback-learning",
    name: "Feedback Learning",
    icon: Activity,
    capability: "LIVE",
    navigable: true,
    group: "Governance",
    component: lazy(() => import("./features/data-console/pages/DataStudioPages").then(m => ({ default: m.FeedbackLearningPage }))),
  },
  {
    path: "/data-console/inventory",
    name: "Inventory",
    icon: Database,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/InventoryPage").then(m => ({ default: m.InventoryPage }))),
  },
  {
    path: "/data-console/inventory/:engine/:assetId",
    name: "Inventory Asset",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/InventoryAssetPage").then(m => ({ default: m.InventoryAssetPage }))),
  },
  {
    path: "/data-console/graph-evidence",
    name: "Graph Evidence",
    icon: FileCheck2,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/GraphEvidencePage").then(m => ({ default: m.GraphEvidencePage }))),
  },
  {
    path: "/data-console/sources",
    name: "Data Sources",
    icon: HardDrive,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/SourcesPage").then(m => ({ default: m.SourcesPage }))),
  },
  {
    path: "/data-console/sources/:sourceId",
    name: "Source Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/SourceDetailPage").then(m => ({ default: m.SourceDetailPage }))),
  },
  {
    path: "/data-console/browser",
    name: "Data Browser",
    icon: Search,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/BrowserLandingPage").then(m => ({ default: m.BrowserLandingPage }))),
  },
  {
    path: "/data-console/browser/:engine/:assetId",
    name: "Asset Browser",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/AssetBrowserPage").then(m => ({ default: m.AssetBrowserPage }))),
  },
  {
    path: "/data-console/browser/:engine/:assetId/records/:recordId",
    name: "Record Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/RecordDetailPage").then(m => ({ default: m.RecordDetailPage }))),
  },
  {
    path: "/data-console/graph",
    name: "Graph Explorer",
    icon: Network,
    capability: "LIVE",
    navigable: true,
    group: "Explore",
    component: lazy(() => import("./features/data-console/pages/graph-explorer/GraphExplorerPage").then(m => ({ default: m.GraphExplorerPage }))),
  },
  {
    path: "/data-console/graph/nodes/:nodeId",
    name: "Graph Node",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/graph-explorer/GraphExplorerPage").then(m => ({ default: m.GraphExplorerPage }))),
  },
  {
    path: "/data-console/graph/relationships/:relationshipId",
    name: "Graph Relationship",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/graph-explorer/GraphExplorerPage").then(m => ({ default: m.GraphExplorerPage }))),
  },
  {
    path: "/data-console/imports",
    name: "Imports",
    icon: Import,
    capability: "LIVE",
    navigable: true,
    group: "Data Operations",
    component: lazy(() => import("./features/data-console/pages/jobs/ImportsListPage").then(m => ({ default: m.ImportsListPage }))),
  },
  {
    path: "/data-console/imports/new",
    name: "New Import",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/jobs/ImportWizardPage").then(m => ({ default: m.ImportWizardPage }))),
  },
  {
    path: "/data-console/imports/:jobId",
    name: "Import Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/jobs/JobDetailPage").then(m => ({ default: m.JobDetailPage }))),
  },
  {
    path: "/data-console/exports",
    name: "Exports",
    icon: Download,
    capability: "LIVE",
    navigable: true,
    group: "Data Operations",
    component: lazy(() => import("./features/data-console/pages/jobs/ExportsListPage").then(m => ({ default: m.ExportsListPage }))),
  },
  {
    path: "/data-console/exports/new",
    name: "New Export",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/jobs/ExportWizardPage").then(m => ({ default: m.ExportWizardPage }))),
  },
  {
    path: "/data-console/exports/:jobId",
    name: "Export Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/jobs/JobDetailPage").then(m => ({ default: m.JobDetailPage }))),
  },
  {
    path: "/data-console/jobs",
    name: "Jobs & Activity",
    icon: Activity,
    capability: "LIVE",
    navigable: true,
    group: "Data Operations",
    component: lazy(() => import("./features/data-console/pages/jobs/JobsListPage").then(m => ({ default: m.JobsListPage }))),
  },
  {
    path: "/data-console/jobs/:jobId",
    name: "Job Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/jobs/JobDetailPage").then(m => ({ default: m.JobDetailPage }))),
  },
  {
    path: "/data-console/workspaces",
    name: "Workspaces",
    icon: Briefcase,
    capability: "LIVE",
    navigable: true,
    group: "Sandbox & AI",
    component: lazy(() => import("./features/data-console/pages/workspaces/WorkspacesListPage").then(m => ({ default: m.WorkspacesListPage }))),
  },
  {
    path: "/data-console/workspaces/new",
    name: "New Workspace",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/workspaces/WorkspaceCreatePage").then(m => ({ default: m.WorkspaceCreatePage }))),
  },
  {
    path: "/data-console/workspaces/:workspaceId",
    name: "Workspace Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/workspaces/WorkspaceDetailPage").then(m => ({ default: m.WorkspaceDetailPage }))),
  },
  {
    path: "/data-console/workspaces/:workspaceId/records/new",
    name: "New Record",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/workspaces/WorkspaceRecordCreatePage").then(m => ({ default: m.WorkspaceRecordCreatePage }))),
  },
  {
    path: "/data-console/workspaces/:workspaceId/records/:recordId/edit",
    name: "Edit Record",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/workspaces/WorkspaceRecordEditPage").then(m => ({ default: m.WorkspaceRecordEditPage }))),
  },
  {
    path: "/data-console/scenarios",
    name: "Scenarios (What-If)",
    icon: Zap,
    capability: "LIVE",
    navigable: true,
    group: "Sandbox & AI",
    component: lazy(() => import("./features/data-console/pages/scenarios/ScenariosListPage").then(m => ({ default: m.ScenariosListPage }))),
  },
  {
    path: "/data-console/scenarios/new",
    name: "New Scenario",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/scenarios/ScenarioCreatePage").then(m => ({ default: m.ScenarioCreatePage }))),
  },
  {
    path: "/data-console/scenarios/:scenarioId",
    name: "Scenario Detail",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/scenarios/ScenarioDetailPage").then(m => ({ default: m.ScenarioDetailPage }))),
  },
  {
    path: "/data-console/scenarios/:scenarioId/compare",
    name: "Scenario Comparison",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/scenarios/ScenarioComparePage").then(m => ({ default: m.ScenarioComparePage }))),
  },
  {
    path: "/data-console/scenarios/:scenarioId/preview",
    name: "Scenario Preview",
    capability: "LIVE",
    navigable: false,
    component: lazy(() => import("./features/data-console/pages/scenarios/ScenarioPreviewPage").then(m => ({ default: m.ScenarioPreviewPage }))),
  },
  {
    path: "/data-console/audit",
    name: "Audit",
    icon: Shield,
    capability: "LIVE",
    navigable: true,
    group: "Governance",
    component: lazy(() => import("./features/data-console/pages/audit/AuditLogsPage").then(m => ({ default: m.AuditLogsPage }))),
  },
  {
    path: "/data-console/governance",
    name: "Governance",
    icon: Shield,
    capability: "LIVE",
    navigable: true,
    group: "Governance",
    component: lazy(() => import("./features/data-console/pages/audit/GovernancePage").then(m => ({ default: m.GovernancePage }))),
  },
  {
    path: "/data-console/settings",
    name: "Settings",
    icon: Settings,
    capability: "LIVE",
    navigable: true,
    group: "Governance",
    component: lazy(() => import("./features/data-console/pages/settings/SettingsPage").then(m => ({ default: m.SettingsPage }))),
  },
  {
    path: "/data-console/hardening",
    name: "Hardening",
    icon: CheckSquare,
    capability: "LIVE",
    navigable: true,
    group: "Governance",
    component: lazy(() => import("./features/data-console/pages/audit/HardeningPage").then(m => ({ default: m.HardeningPage }))),
  }
];
