$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$env:PLATFORM_VAULT_ENABLED = "true"
if (-not $env:PLATFORM_VAULT_ADDRESS) { $env:PLATFORM_VAULT_ADDRESS = "http://127.0.0.1:8200" }
if (-not $env:PLATFORM_VAULT_TOKEN_FILE) { $env:PLATFORM_VAULT_TOKEN_FILE = (Join-Path $Root ".vault-local\return-platform.token") }
$env:PLATFORM_MONGO_DSN_SECRET_REFERENCE = "vault://secret/production/data-sources/mongodb#dsn"
$env:PLATFORM_SOURCE_MONGO_DSN_SECRET_REFERENCE = "vault://secret/production/data-sources/mongodb#source_dsn"
$env:PLATFORM_NEO4J_PASSWORD_SECRET_REFERENCE = "vault://secret/production/data-sources/neo4j#password"
$env:PLATFORM_VALKEY_PASSWORD_SECRET_REFERENCE = "vault://secret/production/data-sources/valkey#password"
$env:PLATFORM_SQLSERVER_PASSWORD_SECRET_REFERENCE = "vault://secret/production/data-sources/sqlserver#password"
$env:PLATFORM_VALIDATION_FINGERPRINT_KEY_SECRET_REFERENCE = "vault://secret/production/platform/validation#fingerprint_key"
