import { useState, type SyntheticEvent } from "react";
import { Database, ShieldCheck, X } from "lucide-react";
import { testSource } from "../../../api/graphAnalyzer";
import type { AnalyzerSource, SourceEngine, SourceInput } from "../../../contracts/graphAnalyzer";

const engineDefaults: Record<SourceEngine, number> = { MONGODB: 27017, POSTGRESQL: 5432, SQLSERVER: 1433, NEO4J: 7687 };

export function SourceDialog({ source, open, saving, error, onClose, onSave }: { readonly source: AnalyzerSource | null; readonly open: boolean; readonly saving: boolean; readonly error: string | null; readonly onClose: () => void; readonly onSave: (input: SourceInput) => void }) {
  const [engine, setEngine] = useState<SourceEngine>(source?.engine ?? "POSTGRESQL");
  const [form, setForm] = useState({ name: "", host: "", port: 5432, database: "", username: "", password: "" });
  const [testing, setTesting] = useState(false);
  const [testResult, setTestResult] = useState<string | null>(null);

  if (!open) return null;
  const input: SourceInput = { ...form, engine, password: form.password || undefined };
  const submit = (event: SyntheticEvent<HTMLFormElement>) => { event.preventDefault(); if (!saving && !testing) onSave(input); };

  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-xl overflow-hidden rounded-2xl border border-emerald-900 bg-[#0c1915] shadow-2xl">
    <header className="flex items-start justify-between border-b border-emerald-950 px-6 py-5"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-950 text-emerald-300"><Database size={19} /></span><div><h2 className="text-lg font-semibold text-white">{source === null ? "Add data source" : "Edit connection"}</h2><p className="mt-0.5 text-sm text-slate-500">Connection configuration only. Source data and schema remain unchanged.</p></div></div><button type="button" onClick={onClose} disabled={saving || testing} className="p-2 text-slate-500 hover:text-white" aria-label="Close"><X size={18} /></button></header>
    <div className="space-y-4 px-6 py-5"><label className="block text-xs font-medium text-slate-400">Database type<select value={engine} onChange={(event) => { const value = event.target.value as SourceEngine; setEngine(value); setForm((current) => ({ ...current, port: engineDefaults[value] })); }} className="mt-1.5 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2.5 text-sm text-white"><option value="POSTGRESQL">PostgreSQL</option><option value="SQLSERVER">Microsoft SQL Server</option><option value="MONGODB">MongoDB</option><option value="NEO4J">Neo4j / graph source</option></select></label>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Connection name" value={form.name} onChange={(name) => { setForm((current) => ({ ...current, name })); }} /><Field label="Host / URI" value={form.host} onChange={(host) => { setForm((current) => ({ ...current, host })); }} /><Field label="Port" type="number" value={String(form.port)} onChange={(port) => { setForm((current) => ({ ...current, port: Number(port) })); }} /><Field label={engine === "MONGODB" ? "Database" : "Database name"} value={form.database} onChange={(database) => { setForm((current) => ({ ...current, database })); }} /><Field label="Username" value={form.username} onChange={(username) => { setForm((current) => ({ ...current, username })); }} /><Field label={source === null ? "Password" : "Password (leave blank to keep saved secret)"} type="password" value={form.password} onChange={(password) => { setForm((current) => ({ ...current, password })); }} required={source === null} /></div>
      <div className="flex items-start gap-2 rounded-lg border border-emerald-900/70 bg-emerald-950/25 p-3 text-xs leading-5 text-emerald-200"><ShieldCheck size={16} className="mt-0.5 shrink-0" /><span>This connection is enforced as read-only for discovery, preview, analysis, and synchronization reads. Credentials are never returned after saving.</span></div>
      {testResult !== null ? <p role="status" className="text-sm text-emerald-300">{testResult}</p> : null}{error !== null ? <p role="alert" className="text-sm text-red-300">Save failed: {error}</p> : null}
    </div>
    <footer className="flex flex-wrap justify-end gap-2 border-t border-emerald-950 bg-[#091511] px-6 py-4"><button type="button" disabled={saving || testing} onClick={onClose} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300 disabled:opacity-50">Cancel</button><button type="button" disabled={saving || testing || !form.host || !form.database} onClick={() => { setTesting(true); setTestResult(null); void testSource(input, source?.id).then((result) => { setTestResult(result.message); }).catch((cause: unknown) => { setTestResult(cause instanceof Error ? cause.message : "Connection test failed."); }).finally(() => { setTesting(false); }); }} className="rounded-lg border border-emerald-700 px-4 py-2 text-sm text-emerald-200 disabled:opacity-50">{testing ? "Testing…" : "Test connection"}</button><button type="submit" disabled={saving || testing || !form.name || !form.host || !form.database || !form.username || (source === null && !form.password)} className="rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-emerald-950 disabled:opacity-50">{saving ? "Saving…" : "Save connection"}</button></footer>
  </form></div>;
}

function Field({ label, value, onChange, type = "text", required = true }: { readonly label: string; readonly value: string; readonly onChange: (value: string) => void; readonly type?: "text" | "password" | "number"; readonly required?: boolean }) {
  return <label className="block text-xs font-medium text-slate-400">{label}<input required={required} type={type} value={value} min={type === "number" ? 1 : undefined} max={type === "number" ? 65535 : undefined} onChange={(event) => { onChange(event.target.value); }} autoComplete={type === "password" ? "new-password" : "off"} className="mt-1.5 w-full rounded-lg border border-emerald-950 bg-[#07120f] px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-700 focus:border-emerald-600" /></label>;
}
